name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Jar With Maven
      run: maven clean package -DskipTests
      working-directory: demo

    - name: Login to Docker Hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

    - name: Build Docker image
      run: docker build -t 101703241/springboot-app:latest .

    - name: Push Docker image
      run: docker push 101703241/springboot-app:latest


